type Emoji = {
  [key: string]: string;
  name: string;
  unicode: string;
  code: string;
};

export const emojis: Emoji[] = [
  {name: 'grinning face', unicode: '😀', code: ':grinning:'},
  {
    name: 'grinning face with big eyes',
    unicode: '😃',
    code: ':smiley:',
  },
  {
    name: 'grinning face with smiling eyes',
    unicode: '😁',
    code: ':grin:',
  },
  {
    name: 'beaming face with smiling eyes',
    unicode: '😊',
    code: ':smile:',
  },
  {
    name: 'grinning squinting face',
    unicode: '😆',
    code: ':laughing:',
  },
  {
    name: 'rolling on the floor laughing',
    unicode: '🤣',
    code: ':rofl:',
  },
  {name: 'face with tears of joy', unicode: '😂', code: ':joy:'},
  {
    name: 'slightly smiling face',
    unicode: '🙂',
    code: ':slightly_smiling_face:',
  },
  {name: 'upside-down face', unicode: '🙃', code: ':upside_down_face:'},
  {name: 'winking face', unicode: '😉', code: ':wink:'},
  {
    name: 'smiling face with smiling eyes',
    unicode: '😊',
    code: ':smile:',
  },
  {name: 'smiling face with halo', unicode: '😇', code: ':innocent:'},
  {
    name: 'smiling face with horns',
    unicode: '😈',
    code: ':smiling_imp:',
  },
  {
    name: 'smiling face with heart-eyes',
    unicode: '😍',
    code: ':heart_eyes:',
  },
  {name: 'face blowing a kiss', unicode: '😘', code: ':kissing_heart:'},
  {name: 'kissing face', unicode: '😗', code: ':kissing:'},
  {
    name: 'smiling face with sunglasses',
    unicode: '😎',
    code: ':sunglasses:',
  },
  {
    name: 'grinning face with sweat',
    unicode: '😅',
    code: ':sweat_smile:',
  },
  {
    name: 'face with rolling eyes',
    unicode: '🙄',
    code: ':rolling_eyes:',
  },
  {name: 'thinking face', unicode: '🤔', code: ':thinking:'},
  {
    name: 'face with head-bandage',
    unicode: '🤕',
    code: ':head_bandage:',
  },
  {
    name: 'face with thermometer',
    unicode: '🤒',
    code: ':thermometer_face:',
  },
  {name: 'face with medical mask', unicode: '😷', code: ':mask:'},
  {name: 'smiling face with mask', unicode: '😷', code: ':mask:'},
  {name: 'flexed biceps', unicode: '💪', code: ':muscle:'},
  {name: 'raised fist', unicode: '✊', code: ':fist:'},
  {name: 'victory hand', unicode: '✌️', code: ':v:'},
  {name: 'ok hand', unicode: '👌', code: ':ok_hand:'},
  {name: 'thumbs up', unicode: '👍', code: ':thumbsup:'},
  {name: 'thumbs down', unicode: '👎', code: ':thumbsdown:'},
  {
    name: 'raised hand with fingers splayed',
    unicode: '🖐️',
    code: ':hand_splayed:',
  },
  {name: 'vulcan salute', unicode: '🖖', code: ':vulcan_salute:'},
  {name: 'clapping hands', unicode: '👏', code: ':clap:'},
  {
    name: 'person raising both hands in celebration',
    unicode: '🙌',
    code: ':raised_hands:',
  },
  {name: 'folded hands', unicode: '🙏', code: ':pray:'},
  {
    name: 'person with folded hands',
    unicode: '🧎',
    code: ':person_kneeling:',
  },
  {name: 'handshake', unicode: '🤝', code: ':handshake:'},

  {name: 'monkey face', unicode: '🐵', code: ':monkey_face:'},
  {name: 'monkey', unicode: '🐒', code: ':monkey:'},
  {name: 'gorilla', unicode: '🦍', code: ':gorilla:'},
  {name: 'dog face', unicode: '🐶', code: ':dog:'},
  {name: 'dog', unicode: '🐕', code: ':dog2:'},
  {name: 'poodle', unicode: '🐩', code: ':poodle:'},
  {name: 'cat face', unicode: '🐱', code: ':cat:'},
  {name: 'cat', unicode: '🐈', code: ':cat2:'},
  {name: 'lion face', unicode: '🦁', code: ':lion:'},
  {name: 'tiger face', unicode: '🐯', code: ':tiger:'},
  {name: 'tiger', unicode: '🐅', code: ':tiger2:'},
  {name: 'leopard', unicode: '🐆', code: ':leopard:'},
  {name: 'horse face', unicode: '🐴', code: ':horse:'},
  {name: 'horse', unicode: '🐎', code: ':racehorse:'},
  {name: 'unicorn face', unicode: '🦄', code: ':unicorn:'},
  {name: 'zebra', unicode: '🦓', code: ':zebra:'},
  {name: 'deer', unicode: '🦌', code: ':deer:'},
  {name: 'cow face', unicode: '🐮', code: ':cow:'},
  {name: 'ox', unicode: '🐂', code: ':ox:'},
  {name: 'water buffalo', unicode: '🐃', code: ':water_buffalo:'},
  {name: 'cow', unicode: '🐄', code: ':cow2:'},
  {name: 'pig face', unicode: '🐷', code: ':pig:'},
  {name: 'pig', unicode: '🐖', code: ':pig2:'},
  {name: 'boar', unicode: '🐗', code: ':boar:'},
  {name: 'goat', unicode: '🐐', code: ':goat:'},
  {name: 'ram', unicode: '🐏', code: ':ram:'},
  {name: 'ewe', unicode: '🐑', code: ':sheep:'},
  {name: 'llama', unicode: '🦙', code: ':llama:'},
  {name: 'giraffe', unicode: '🦒', code: ':giraffe:'},
  {name: 'elephant', unicode: '🐘', code: ':elephant:'},
  {name: 'rhinoceros', unicode: '🦏', code: ':rhinoceros:'},
  {name: 'hippopotamus', unicode: '🦛', code: ':hippopotamus:'},
  {name: 'mouse face', unicode: '🐭', code: ':mouse:'},
  {name: 'mouse', unicode: '🐁', code: ':mouse2:'},
  {name: 'rat', unicode: '🐀', code: ':rat:'},
  {name: 'hamster face', unicode: '🐹', code: ':hamster:'},
  {name: 'rabbit face', unicode: '🐰', code: ':rabbit:'},
  {name: 'rabbit', unicode: '🐇', code: ':rabbit2:'},
  {name: 'chipmunk', unicode: '🐿️', code: ':chipmunk:'},
  {name: 'hedgehog', unicode: '🦔', code: ':hedgehog:'},
  {name: 'bat', unicode: '🦇', code: ':bat:'},
  {name: 'bear face', unicode: '🐻', code: ':bear:'},
  {name: 'koala', unicode: '🐨', code: ':koala:'},
  {name: 'panda face', unicode: '🐼', code: ':panda_face:'},
  {name: 'feet', unicode: '🐾', code: ':feet:'},
  {name: 'bird', unicode: '🐦', code: ':bird:'},
  {name: 'baby chick', unicode: '🐤', code: ':baby_chick:'},
  {
    name: 'front-facing baby chick',
    unicode: '🐥',
    code: ':hatching_chick:',
  },
  {name: 'bird', unicode: '🐣', code: ':egg:'},
  {name: 'penguin', unicode: '🐧', code: ':penguin:'},
  {name: 'dove', unicode: '🕊️', code: ':dove:'},
  {name: 'eagle', unicode: '🦅', code: ':eagle:'},
  {name: 'duck', unicode: '🦆', code: ':duck:'},
  {name: 'swan', unicode: '🦢', code: ':swan:'},
  {name: 'owl', unicode: '🦉', code: ':owl:'},
  {name: 'peacock', unicode: '🦚', code: ':peacock:'},
  {name: 'parrot', unicode: '🦜', code: ':parrot:'},
  {name: 'frog', unicode: '🐸', code: ':frog:'},
  {name: 'crocodile', unicode: '🐊', code: ':crocodile:'},
  {name: 'turtle', unicode: '🐢', code: ':turtle:'},
  {name: 'snake', unicode: '🐍', code: ':snake:'},
  {name: 'dragon face', unicode: '🐲', code: ':dragon_face:'},
  {name: 'dragon', unicode: '🐉', code: ':dragon:'},
  {name: 'sauropod', unicode: '🦕', code: ':sauropod:'},
  {name: 'T-Rex', unicode: '🦖', code: ':t-rex:'},
  {name: 'spouting whale', unicode: '🐳', code: ':whale:'},
  {name: 'whale', unicode: '🐋', code: ':whale2:'},
  {name: 'dolphin', unicode: '🐬', code: ':dolphin:'},
  {name: 'seal', unicode: '🦭', code: ':seal:'},
  {name: 'fish', unicode: '🐟', code: ':fish:'},
  {name: 'tropical fish', unicode: '🐠', code: ':tropical_fish:'},
  {name: 'blowfish', unicode: '🐡', code: ':blowfish:'},
  {name: 'shark', unicode: '🦈', code: ':shark:'},
  {name: 'octopus', unicode: '🐙', code: ':octopus:'},
  {name: 'spiral shell', unicode: '🐚', code: ':shell:'},
  {name: 'snail', unicode: '🐌', code: ':snail:'},
  {name: 'butterfly', unicode: '🦋', code: ':butterfly:'},
  {name: 'bug', unicode: '🐛', code: ':bug:'},
  {name: 'ant', unicode: '🐜', code: ':ant:'},
  {name: 'honeybee', unicode: '🐝', code: ':bee:'},
  {name: 'beetle', unicode: '🪲', code: ':beetle:'},
  {name: 'lady beetle', unicode: '🐞', code: ':lady_beetle:'},
  {name: 'cricket', unicode: '🦗', code: ':cricket:'},
  {name: 'cockroach', unicode: '🪳', code: ':cockroach:'},
  {name: 'spider', unicode: '🕷️', code: ':spider:'},
  {name: 'spider web', unicode: '🕸️', code: ':spider_web:'},
  {name: 'scorpion', unicode: '🦂', code: ':scorpion:'},
  {name: 'mosquito', unicode: '🦟', code: ':mosquito:'},
  {name: 'microbe', unicode: '🦠', code: ':microbe:'},

  {name: 'grapes', unicode: '🍇', code: ':grapes:'},
  {name: 'melon', unicode: '🍈', code: ':melon:'},
  {name: 'watermelon', unicode: '🍉', code: ':watermelon:'},
  {name: 'tangerine', unicode: '🍊', code: ':tangerine:'},
  {name: 'lemon', unicode: '🍋', code: ':lemon:'},
  {name: 'banana', unicode: '🍌', code: ':banana:'},
  {name: 'pineapple', unicode: '🍍', code: ':pineapple:'},
  {name: 'mango', unicode: '🥭', code: ':mango:'},
  {name: 'red apple', unicode: '🍎', code: ':apple:'},
  {name: 'green apple', unicode: '🍏', code: ':green_apple:'},
  {name: 'pear', unicode: '🍐', code: ':pear:'},
  {name: 'peach', unicode: '🍑', code: ':peach:'},
  {name: 'cherries', unicode: '🍒', code: ':cherries:'},
  {name: 'strawberry', unicode: '🍓', code: ':strawberry:'},
  {name: 'kiwi fruit', unicode: '🥝', code: ':kiwi:'},
  {name: 'tomato', unicode: '🍅', code: ':tomato:'},
  {name: 'coconut', unicode: '🥥', code: ':coconut:'},
  {name: 'avocado', unicode: '🥑', code: ':avocado:'},
  {name: 'eggplant', unicode: '🍆', code: ':eggplant:'},
  {name: 'potato', unicode: '🥔', code: ':potato:'},
  {name: 'carrot', unicode: '🥕', code: ':carrot:'},
  {name: 'corn', unicode: '🌽', code: ':corn:'},
  {name: 'hot pepper', unicode: '🌶️', code: ':hot_pepper:'},
  {name: 'bell pepper', unicode: '🫑', code: ':bell_pepper:'},
  {name: 'cucumber', unicode: '🥒', code: ':cucumber:'},
  {name: 'leafy green', unicode: '🥬', code: ':leafy_green:'},
  {name: 'broccoli', unicode: '🥦', code: ':broccoli:'},
  {name: 'garlic', unicode: '🧄', code: ':garlic:'},
  {name: 'onion', unicode: '🧅', code: ':onion:'},
  {name: 'mushroom', unicode: '🍄', code: ':mushroom:'},
  {name: 'peanuts', unicode: '🥜', code: ':peanuts:'},
  {name: 'chestnut', unicode: '🌰', code: ':chestnut:'},
  {name: 'bread', unicode: '🍞', code: ':bread:'},
  {name: 'croissant', unicode: '🥐', code: ':croissant:'},
  {name: 'baguette bread', unicode: '🥖', code: ':baguette_bread:'},
  {name: 'pretzel', unicode: '🥨', code: ':pretzel:'},
  {name: 'bagel', unicode: '🥯', code: ':bagel:'},
  {name: 'pancakes', unicode: '🥞', code: ':pancakes:'},
  {name: 'cheese wedge', unicode: '🧀', code: ':cheese_wedge:'},
  {name: 'meat on bone', unicode: '🍖', code: ':meat_on_bone:'},
  {name: 'poultry leg', unicode: '🍗', code: ':poultry_leg:'},
  {name: 'cut of meat', unicode: '🥩', code: ':cut_of_meat:'},
  {name: 'bacon', unicode: '🥓', code: ':bacon:'},
  {name: 'hamburger', unicode: '🍔', code: ':hamburger:'},
  {name: 'french fries', unicode: '🍟', code: ':fries:'},
  {name: 'pizza', unicode: '🍕', code: ':pizza:'},
  {name: 'hot dog', unicode: '🌭', code: ':hotdog:'},
  {name: 'sandwich', unicode: '🥪', code: ':sandwich:'},
  {name: 'taco', unicode: '🌮', code: ':taco:'},
  {name: 'burrito', unicode: '🌯', code: ':burrito:'},
  {name: 'tamale', unicode: '🫔', code: ':tamale:'},
  {
    name: 'stuffed flatbread',
    unicode: '🥙',
    code: ':stuffed_flatbread:',
  },
  {name: 'falafel', unicode: '🧆', code: ':falafel:'},
  {name: 'egg', unicode: '🥚', code: ':egg:'},
  {name: 'cooking', unicode: '🍳', code: ':cooking:'},
  {
    name: 'shallow pan of food',
    unicode: '🥘',
    code: ':shallow_pan_of_food:',
  },
  {name: 'pot of food', unicode: '🍲', code: ':stew:'},
  {name: 'fondue', unicode: '🫕', code: ':fondue:'},
  {name: 'bowl with spoon', unicode: '🥣', code: ':bowl_with_spoon:'},
  {name: 'green salad', unicode: '🥗', code: ':green_salad:'},
  {name: 'popcorn', unicode: '🍿', code: ':popcorn:'},
  {name: 'butter', unicode: '🧈', code: ':butter:'},
  {name: 'salt', unicode: '🧂', code: ':salt:'},
  {name: 'canned food', unicode: '🥫', code: ':canned_food:'},
  {name: 'bento box', unicode: '🍱', code: ':bento:'},
  {name: 'rice cracker', unicode: '🍘', code: ':rice_cracker:'},
  {name: 'rice ball', unicode: '🍙', code: ':rice_ball:'},
  {name: 'cooked rice', unicode: '🍚', code: ':rice:'},
  {name: 'curry rice', unicode: '🍛', code: ':curry:'},
  {name: 'steaming bowl', unicode: '🍜', code: ':ramen:'},
  {name: 'spaghetti', unicode: '🍝', code: ':spaghetti:'},
];

export default emojis;
